title: "Graph Neural Networks (GNNs) using PyTorch-Geometric (PyG)"
author: SMU O'Donnell Data Science and Research Computing Institute
logo: logo.webp
copyright: "2025"

execute:
  execute_notebooks: force

repository:
  url: "https://github.com/SouthernMethodistUniversity/pyg"
  path_to_book: docs
  branch: main

html:
  use_issues_button: true
  use_repository_button: true

